name: Hello ZeroOps 
on : 
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
        env:
          PROJECT_NAME: "ZeroOps"
          AUTHOR: "DevOpsTeam"      

      - run: echo $PROJECT_NAME by $AUTHOR
 