name: Hello ZeroOps 
on : 
  pull_request:
  push:
    branches: [main]
env:
    PROJECT_NAME: 'DEV_OPS'
    API_KEY: ${{ secrets.API_KEY }}
jobs:
  backend:
    
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
            

      - run: |
            'echo $PROJECT_NAME'
            pip install pytest
            python -m pytest
            echo 'Success'

 